# ECON526: Assignment 2

## Student Name/Number: Gauthem Arvind Pradeep, 96038302

### Instructions

-   Ensure you modify the field above with your **name and student
    number above immediately**
-   Modify directly and save as the `.ipynb`, and submit directly. Do
    not export to PDF or HTML, and leave the filename as is. Canvas will
    automatically append your name to the filename.
-   Submit directly to canvas as a `.ipynb` file.

## Setup

Use the following packages and imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from numpy.linalg import cond, matrix_rank, norm
from scipy.linalg import inv, solve, det, eig, lu, eigvals
from scipy.linalg import solve_triangular, eigvalsh, cholesky

## Q1.1

Generate a random matrix $A \in \mathbb{R}^{10\times 10}$ and random
vector $b\in\mathbb{R}^{10}$ of uniformly distributed floating points
between 0 and 1. Hint: use `np.random.rand(10, 10)`

and solve $A x = b$ as a linear system with

1.  `scipy.linalg.solve`
2.  `scipy.linalg.inv`

Modify

In [2]:
N = 10
A = np.random.rand(N,N)
b = np.random.rand(N)
x_solve = scipy.linalg.solve(A,b)
A_inv = scipy.linalg.inv(A)
x_inv = A_inv @ b
print(f"Solve = {x_solve} \n Inv = {x_inv}")


Solve = [-1.92536549 -0.2405554   0.54527656 -1.1792923   1.46662598 -0.58880388
  0.22395118  0.69874033  0.75077996  1.65283251] 
 Inv = [-1.92536549 -0.2405554   0.54527656 -1.1792923   1.46662598 -0.58880388
  0.22395118  0.69874033  0.75077996  1.65283251]


What matrix decomposition would `scipy.linalg.solve` likely use in this
case?

LU decomposition

## Q1.2

The product of any matrix with its transpose is symmetric. Prove it.
Hint: the definition of symmetric matrix $B$ is if $B = B^T$. Use this
to take the transpose of $B \equiv A^T A$.

$$
\text{Let } A \text{ be a matrix with transpose } A^\top \\
\text{A symmetric matrix X is one such that } X = X^\top \\
\text{Suppose } X = A^\top A \\
\implies X^\top = (A^\top A)^\top = A^\top (A^\top)^\top \\
\text{But we know that the transpose of a transpose is the original matrix itself} \\
\implies X^\top = A^\top A = X \\
\implies \text{The product of any matrix with its transpose is symmetric}
$$

## Q1.3

Using your matrix $A$ from before, construct the symmetric $B = A^T A$.

Verify it is symmetric, and then find out if it is positive definite.
Hint: you will need to use `eigvals` or `eigs`.

In [3]:
B = A.T @ A
print(f"Is B symmetric? {np.array_equal(B.T, B)}")
B_eigs = eigvalsh(B)
print(B_eigs)
print(f"Is matrix B is positive definite? {np.all(B_eigs > 0)}")

Is B symmetric? True
[5.62739353e-03 2.77054595e-02 8.50851529e-02 1.86563469e-01
 4.22246947e-01 7.92575994e-01 1.09582261e+00 1.52823424e+00
 1.77780413e+00 2.72843464e+01]
Is matrix B is positive definite? True


## Q1.4

Now solve the system $B x = b$ using `solve` and `inv`. If the matrix
was shown to be symmetric or positive definite before, then use that in
your solution

In [4]:
x_solve = solve(B, b, assume_a= "pos")
L = cholesky(B, lower = True) #can only be used if matrix is positive definite
y = inv(L) @ b
x_inv = inv(L.T) @ y
print(f"Solve = {x_solve} \n Inv = {x_inv}")


Solve = [-14.71967526  -6.97793235   0.09631141 -10.8063208    9.30960997
   0.55381241   3.2784164   -2.92746534   9.10945237  14.0947329 ] 
 Inv = [-14.71967526  -6.97793235   0.09631141 -10.8063208    9.30960997
   0.55381241   3.2784164   -2.92746534   9.10945237  14.0947329 ]


## Q2.1

Take the matrix $A \in \mathbb{R}^{100 \times 5}$

Check if it is full rank

In [5]:
# modify here
N = 100
K = 5
A = np.random.rand(N, K)
rank = matrix_rank(A)
print(f"Is A full rank? {rank == K}")


Is A full rank? True


## Q2.2

Take that previous matrix in Q2.1 and append a new column to it, so that
it is now $\hat{A} \in \mathbb{R}^{100 \times 6}$ such that the matrix
will still have a rank of $5$ and not 6. Hint: lots of ways to append a
vector to a matrix in numpy, including `numpy.column_stack` and
`numpy.concatenate`

In [6]:
a = np.random.rand(N,1)
dep = A[:,3]*6
dep = dep.reshape(N,1)
A_hat = np.concatenate((A,dep), axis = 1)
matrix_rank(A_hat)

5

## Q2.3

Take the $A$ and the $\hat{A}$ from before, and form $B = A A^T$ and
$\hat{B} = \hat{A} \hat{A}^T$. What are there ranks?

In [7]:
B = A @ A.T
B_hat = A_hat @ A_hat.T
print(matrix_rank(B), matrix_rank(B_hat))

5 5


Could we do a cholesky decomposition of this matrix? Check and/or
explain why not if you can’t

In [8]:
for mat in [B, B_hat]:
    try:
        L = cholesky(mat, lower = True)
        if np.allclose(L @ L.T, mat):
            print(f"The matrix {mat} is positive definite")
    except np.linalg.LinAlgError:
            print(f"The matrix {mat} is not positive definite, so a Cholesky decomposition will not work")

The matrix [[1.34982623 0.56202202 0.33440342 ... 0.69950901 0.31871941 1.31487696]
 [0.56202202 0.31068967 0.35057676 ... 0.54439797 0.24390903 0.75037495]
 [0.33440342 0.35057676 0.92075365 ... 0.93829523 0.63157945 1.136895  ]
 ...
 [0.69950901 0.54439797 0.93829523 ... 1.50969264 0.66181294 1.38490745]
 [0.31871941 0.24390903 0.63157945 ... 0.66181294 0.4901498  0.85767357]
 [1.31487696 0.75037495 1.136895   ... 1.38490745 0.85767357 2.20625192]] is not positive definite, so a Cholesky decomposition will not work
The matrix [[ 2.85004577  1.07753361  0.77780702 ...  5.04013741  1.65202424
   1.92920094]
 [ 1.07753361  0.48783188  0.50294092 ...  2.0359425   0.7020647
   0.96147147]
 [ 0.77780702  0.50294092  1.05180563 ...  2.22120764  1.02564989
   1.31846407]
 ...
 [ 5.04013741  2.0359425   2.22120764 ... 14.06855784  4.5195022
   3.16234872]
 [ 1.65202424  0.7020647   1.02564989 ...  4.5195022   1.67511087
   1.40364775]
 [ 1.92920094  0.96147147  1.31846407 ...  3.16234872  1.4

## Q3.1

Take the following $B\in\mathbb{R}^{N\times N}$ symmetric matrix and do
an eigendecomposition (spectral decomposition in this case since
symmetric), and print out the eigenvalues

In [9]:
N = 10
A = 2.0 * np.random.rand(N, N)
B = A.T @ A

Lambda, Q = eig(B)
print(f"eigenvectors are column-by-column in Q =\n{Q}")
print(f"eigenvalues are in Lambda = {Lambda}")
QLQ = Q @ np.diag(np.real(Lambda)) @ Q.T
print(f"Q Lambda Q^T =\n{QLQ}")
print(f"Is A = Q Lambda Q^T? {np.allclose(QLQ, B)}")

eigenvectors are column-by-column in Q =
[[ 0.38429208  0.33598558  0.09444257 -0.05431447  0.20937603 -0.37056376
   0.37899523  0.61879437  0.14080011 -0.0062835 ]
 [ 0.34817672 -0.40645442 -0.1592227  -0.26608016  0.33094627  0.27149446
   0.20141504 -0.09380129  0.08885755 -0.61393829]
 [ 0.30987785 -0.40337089  0.42875003 -0.04081137 -0.51595892  0.32656522
   0.16718085  0.17842415  0.21828607  0.27474283]
 [ 0.36976552  0.51621942  0.02229757 -0.07641992 -0.56295491 -0.01826651
  -0.04166947 -0.2841435  -0.15373575 -0.40877052]
 [ 0.32606636 -0.35304032  0.16305183 -0.11909821  0.06233532 -0.67393942
   0.01259151 -0.42724854 -0.21641495  0.20163744]
 [ 0.3050277  -0.13692272 -0.58333531 -0.15245376 -0.1775221  -0.11790208
  -0.57870612  0.24908992  0.24967321  0.14138517]
 [ 0.20986925 -0.12413755 -0.45895743  0.351321   -0.09652541  0.17499786
   0.32720476  0.12237636 -0.6392192   0.18945944]
 [ 0.29990706  0.13251854  0.39375715 -0.13376418  0.35345133  0.30121268
  -0.51186

## Q3.2

For your matrix above, calculate its spectral radius

In [10]:
spectral_radius = np.max(np.abs(Lambda))
print(f"The spectral radius of B is {spectral_radius}")

The spectral radius of B is 116.84426823044788


## Q4.1

Take the vector $\hat{x}_1\in \mathbb{R}^2$

In [11]:
x_hat_1 = np.array([1, 2])

Verify that it is not a unit length vector (i.e. $\|\hat{x}_1\| \neq 1$)
then create a new $x_1$ that is a unit length vector in the same
direction as $\hat{x}_1$ (i.e. $||x_1|| = 1$)

In [12]:
print(f"Is the length of x_hat_1 = 1? {norm(x_hat_1) == 1}")
x_1 = x_hat_1 / norm(x_hat_1)
print(x_1)
print(f"What is the norm of x_1 = 1? {norm(x_1)}")

Is the length of x_hat_1 = 1? False
[0.4472136  0.89442719]
What is the norm of x_1 = 1? 0.9999999999999999


## Q4.2

Now find a $x_2$ which is also a unit length vector, but is orthogonal
to $x_1$. Check it with `np.dot(x_1, x_2)` approx 0 and `norm(x_2)`
approx 1. Hint: many ways to do this by hand in $\mathbb{R}^2$ and
fulfill the requirements, such as simple rotations.

In [13]:
x_2 = np.array([2,-1]) / norm(x_hat_1)
print(f"What is the norm of x_1 = 1? {norm(x_1)}")
print(f"What is the dot product between x_1 and x_2? {np.dot(x_1,x_2)}")


What is the norm of x_1 = 1? 0.9999999999999999
What is the dot product between x_1 and x_2? 0.0


## Q4.3

The vectors $x_1$ and $x_2$ are now an orthonormal set. Form the matrix
$Q = \begin{bmatrix} x_1 & | & x_2\end{bmatrix}$ and verify the
condition for orthonormality (i.e. $Q^T Q = I\implies Q^{-1} = Q^T$)

In [14]:
Q = np.column_stack((x_1, x_2))
QTQ = Q.T @ Q
I = np.eye(QTQ.shape[0])
print(f"Is Q^T * Q is equal to I? {np.allclose(QTQ, I)}")

Is Q^T * Q is equal to I? True


## Q4.4

Create a matrix $A$ such that: 1. $Q$ are its eigenvectors 2. The
spectral radius of $A$ is $1.0$ 3. $A$ is positive definite.

Hint: create a matrix of eigenvalues $\Lambda$ and then do an
eigendecomposition in reverse

In [15]:
diag = [1,0.3] # maximum absolute eigenvalue is 1 and both eigenvalues are positive so spactral radius is 1 and matrix is positive definite
Lambda = np.diag(diag)
A = Q @ Lambda @ Q.T
print(f"Q = {Q},\n Lambda = {Lambda},\n Q^T = {Q.T}")
print(f"A={A}")
eigvalues, eigvectors = eig(A)
print(f"Eigenvalues of A = {eigvalues} \n Eigenvectors of A = {eigvectors}")


[[0.44 0.28]
 [0.28 0.86]]
