# ECON526: Assignment 2

## Student Name/Number: Gauthem Arvind Pradeep, 96038302

### Instructions

-   Ensure you modify the field above with your **name and student
    number above immediately**
-   Modify directly and save as the `.ipynb`, and submit directly. Do
    not export to PDF or HTML, and leave the filename as is. Canvas will
    automatically append your name to the filename.
-   Submit directly to canvas as a `.ipynb` file.

## Setup

Use the following packages and imports

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from numpy.linalg import cond, matrix_rank, norm
from scipy.linalg import inv, solve, det, eig, lu, eigvals
from scipy.linalg import solve_triangular, eigvalsh, cholesky

## Q1.1

Generate a random matrix $A \in \mathbb{R}^{10\times 10}$ and random
vector $b\in\mathbb{R}^{10}$ of uniformly distributed floating points
between 0 and 1. Hint: use `np.random.rand(10, 10)`

and solve $A x = b$ as a linear system with

1.  `scipy.linalg.solve`
2.  `scipy.linalg.inv`

Modify

In [71]:
N = 10
A = np.random.rand(N,N)
b = np.random.rand(N)
x_solve = scipy.linalg.solve(A,b)
A_inv = scipy.linalg.inv(A)
x_inv = A_inv @ b
print(f"Solve = {x_solve} \n Inv = {x_inv}")


Solve = [  0.30088253   8.33325729  -1.63319803  10.27949328  -2.39181396
 -10.25663498   7.37771413  -0.84102048  -9.36759822   1.13848971] 
 Inv = [  0.30088253   8.33325729  -1.63319803  10.27949328  -2.39181396
 -10.25663498   7.37771413  -0.84102048  -9.36759822   1.13848971]


What matrix decomposition would `scipy.linalg.solve` likely use in this
case?

LU decomposition

## Q1.2

The product of any matrix with its transpose is symmetric. Prove it.
Hint: the definition of symmetric matrix $B$ is if $B = B^T$. Use this
to take the transpose of $B \equiv A^T A$.

$$
\text{Let } A \text{ be a matrix with transpose } A^\top \\
\text{A symmetric matrix X is one such that } X = X^\top \\
\text{Suppose } X = A^\top A \\
\implies X^\top = (A^\top A)^\top = A^\top (A^\top)^\top \\
\text{But we know that the transpose of a transpose is the original matrix itself} \\
\implies X^\top = A^\top A = X \\
\implies \text{The product of any matrix with its transpose is symmetric}
$$

## Q1.3

Using your matrix $A$ from before, construct the symmetric $B = A^T A$.

Verify it is symmetric, and then find out if it is positive definite.
Hint: you will need to use `eigvals` or `eigs`.

In [99]:
B = A.T @ A
print(f"Is B symmetric? {np.array_equal(B.T, B)}")
B_eigs = eigvalsh(B)
print(B_eigs)
print(f"Is matrix B is positive definite? {np.all(B_eigs > 0)}")

Is B symmetric? True
[  5.73867296   7.06824646   8.65384352   9.6266195  138.34048441]
Is matrix B is positive definite? True


## Q1.4

Now solve the system $B x = b$ using `solve` and `inv`. If the matrix
was shown to be symmetric or positive definite before, then use that in
your solution

In [73]:
x_solve = solve(B, b, assume_a= "pos")
y = inv(L) @ b
x_inv = inv(L.T) @ y

print(f"Solve = {x_solve} \n Inv = {x_inv}")


Solve = [  17.08583858 -255.85639672   42.37727687 -303.57459741   83.91504761
  277.16300568 -201.99611851   24.84848556  278.49243683   -9.27099601] 
 Inv = [  17.08583858 -255.85639672   42.37727687 -303.57459741   83.91504761
  277.16300568 -201.99611851   24.84848556  278.49243683   -9.27099601]


## Q2.1

Take the matrix $A \in \mathbb{R}^{100 \times 5}$

Check if it is full rank

In [74]:
# modify here
N = 100
K = 5
A = np.random.rand(N, K)
rank = matrix_rank(A)
print(f"Is A full rank? {rank == K}")


Is A full rank? True


## Q2.2

Take that previous matrix in Q2.1 and append a new column to it, so that
it is now $\hat{A} \in \mathbb{R}^{100 \times 6}$ such that the matrix
will still have a rank of $5$ and not 6. Hint: lots of ways to append a
vector to a matrix in numpy, including `numpy.column_stack` and
`numpy.concatenate`

In [87]:
a = np.random.rand(N,1)
dep = A[:,3]*6
dep = dep.reshape(N,1)
A_hat = np.concatenate((A,dep), axis = 1)
matrix_rank(A_hat)

5

## Q2.3

Take the $A$ and the $\hat{A}$ from before, and form $B = A A^T$ and
$\hat{B} = \hat{A} \hat{A}^T$. What are there ranks?

In [96]:
B = A @ A.T
B_hat = A_hat @ A_hat.T
print(matrix_rank(B), matrix_rank(B_hat))

5 5


Could we do a cholesky decomposition of this matrix? Check and/or
explain why not if you can’t

In [103]:
for mat in [B, B_hat]:
    try:
        L = cholesky(mat, lower = True)
        if np.allclose(L @ L.T, mat):
            print(f"The matrix {mat} is positive definite")
    except np.linalg.LinAlgError:
            print(f"The matrix {mat} is not positive definite, so a Cholesky decomposition will not work")

The matrix [[33.37307344 26.4539975  24.9244946  28.04083291 25.76780316]
 [26.4539975  34.86669706 26.26636594 27.38824081 24.85194508]
 [24.9244946  26.26636594 32.43916958 26.1846939  25.70803688]
 [28.04083291 27.38824081 26.1846939  35.76747782 25.38390094]
 [25.76780316 24.85194508 25.70803688 25.38390094 32.98144894]] is positive definite
The matrix [[10.68583364 16.28325552 17.53291604 ... 17.1064749  14.92976903
  18.84663747]
 [16.28325552 27.22437639 28.95278477 ... 28.10432026 24.58802005
  30.16807589]
 [17.53291604 28.95278477 31.84844487 ... 30.67403207 26.93608307
  32.92813315]
 ...
 [17.1064749  28.10432026 30.67403207 ... 29.8273533  26.11557937
  32.20479931]
 [14.92976903 24.58802005 26.93608307 ... 26.11557937 23.18520154
  28.23959498]
 [18.84663747 30.16807589 32.92813315 ... 32.20479931 28.23959498
  35.12194958]] is not positive definite, so a Cholesky decomposition will not work


## Q3.1

Take the following $B\in\mathbb{R}^{N\times N}$ symmetric matrix and do
an eigendecomposition (spectral decomposition in this case since
symmetric), and print out the eigenvalues

In [107]:
N = 10
A = 2.0 * np.random.rand(N, N)
B = A.T @ A

Lambda, Q = eig(B)
print(f"eigenvectors are column-by-column in Q =\n{Q}")
print(f"eigenvalues are in Lambda = {Lambda}")
QLQ = Q @ np.diag(np.real(Lambda)) @ Q.T
print(f"Q Lambda Q^T =\n{QLQ}")
print(f"Is A = Q Lambda Q^T? {np.allclose(QLQ, B)}")

eigenvectors are column-by-column in Q =
[[ 0.2649827   0.262182   -0.22408295  0.50829423 -0.08836734  0.09208395
  -0.29032736  0.28478029  0.60678287 -0.05104013]
 [ 0.27065369 -0.2871758  -0.47320277 -0.02756711  0.08844092  0.38347307
   0.25357015 -0.11046455 -0.06999399 -0.61913088]
 [ 0.29230741 -0.15184329  0.27446424  0.33221302  0.75497163 -0.04608285
  -0.20910307  0.11310476 -0.27697767 -0.02155656]
 [ 0.32272851  0.01141992  0.16002213 -0.56418121  0.00230132  0.53841734
  -0.19145731  0.42182818  0.03296216  0.21500797]
 [ 0.33722078  0.25885222 -0.49759387 -0.27993534  0.14485901 -0.22058942
  -0.38150038 -0.45801862 -0.1010957   0.2410943 ]
 [ 0.35748989  0.23675342  0.17744429 -0.32164882  0.21446408 -0.45296081
   0.50974436  0.0908483   0.36321622 -0.17325495]
 [ 0.35208433 -0.62060279 -0.208481    0.07319517 -0.30295921 -0.39274717
   0.05565882  0.31292498 -0.10426023  0.2900727 ]
 [ 0.20519572  0.49564035  0.01998649  0.0964111  -0.33118007 -0.14974837
  -0.04652

## Q3.2

For your matrix above, calculate its spectral radius

In [108]:
spectral_radius = np.max(np.abs(Lambda))
print(f"The spectral radius of B is {spectral_radius}")

The spectral radius of B is 105.66922225634593


## Q4.1

Take the vector $\hat{x}_1\in \mathbb{R}^2$

In [111]:
x_hat_1 = np.array([1, 2])

Verify that it is not a unit length vector (i.e. $\|\hat{x}_1\| \neq 1$)
then create a new $x_1$ that is a unit length vector in the same
direction as $\hat{x}_1$ (i.e. $||x_1|| = 1$)

In [119]:
print(f"Is the length of x_hat_1 = 1? {norm(x_hat_1) == 1}")
x_1 = x_hat_1 / norm(x_hat_1)
print(x_1)
print(f"What is the norm of x_1 = 1? {norm(x_1)}")

Is the length of x_hat_1 = 1? False
[0.4472136  0.89442719]
Is the length of x_1 = 1? 0.9999999999999999


## Q4.2

Now find a $x_2$ which is also a unit length vector, but is orthogonal
to $x_1$. Check it with `np.dot(x_1, x_2)` approx 0 and `norm(x_2)`
approx 1. Hint: many ways to do this by hand in $\mathbb{R}^2$ and
fulfill the requirements, such as simple rotations.

In [122]:
x_2 = np.array([2,-1]) / norm(x_hat_1)
print(f"What is the norm of x_1 = 1? {norm(x_1)}")
print(f"What is the dot product between x_1 and x_2? {np.dot(x_1,x_2)}")


What is the norm of x_1 = 1? 0.9999999999999999
What is the dot product between x_1 and x_2? 0.0


## Q4.3

The vectors $x_1$ and $x_2$ are now an orthonormal set. Form the matrix
$Q = \begin{bmatrix} x_1 & | & x_2\end{bmatrix}$ and verify the
condition for orthonormality (i.e. $Q^T Q = I\implies Q^{-1} = Q^T$)

In [143]:
Q = np.column_stack((x_1, x_2))
QTQ = Q.T @ Q
I = np.eye(QTQ.shape[0])
print(f"Is Q^T * Q is equal to I? {np.allclose(QTQ, I)}")

Is Q^T * Q is equal to I? True


## Q4.4

Create a matrix $A$ such that: 1. $Q$ are its eigenvectors 2. The
spectral radius of $A$ is $1.0$ 3. $A$ is positive definite.

Hint: create a matrix of eigenvalues $\Lambda$ and then do an
eigendecomposition in reverse

In [153]:
diag = [1, 0.3] # maximum absolute eigenvalue is 1 and both eigenvalues are positive so spactral radius is 1 and matrix is positive definite
Lambda = np.diag(diag)
A = Q @ Lambda @ Q.T
print(A)


[[0.44 0.28]
 [0.28 0.86]]
